### PR TITLE
Update event method signatures: Integer to EventType

### PR DESCRIPTION
**Pull request by awoods**
Related to: https://jira.duraspace.org/browse/FCREPO-1848

### CODE REVIEW

**Comment by awoods** [comment]
@acoburn, please merge this PR.

**Comment by ajs6f** [comment]
Is `EventType` our type?

**Comment by awoods** [comment]
@ajs6f, yes: https://github.com/fcrepo4/fcrepo4/blob/master/fcrepo-kernel-api/src/main/java/org/fcrepo/kernel/api/utils/EventType.java

**Comment by ajs6f** [comment]
Super +1 to whoever did that, and +1 to this.

**Comment by ajs6f** [comment]
Although we additionally need to disconnect the JCR integers from that type and probably also assign URIs to connect the values in that enumeration with some published ontology.

**Comment by acoburn** [comment]
@ajs6f yes, exactly. IMO, the language of these event types should also be aligned with the fedora api (e.g. NODE_ADDED could become RESOURCE_ADDED). Changing the `FedoraEvent` signature to use `EventType` values rather than simple integers is just one step in that direction.

**Comment by ajs6f** [comment]
@acoburn Yep. Generally speaking, Fedora is itself just one step in the direction of Fedora.

**Pull request merged**
